<?php // Options page - requires Advanced Custom Fields Plugin
if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_542986452cf69',
	'title' => 'Social Networks',
	'fields' => array (
		array (
			'key' => 'field_54ee149552273',
			'label' => 'Icon Size',
			'name' => 'icon_size',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => 'Choose the icon size "in pixels"',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'fifty' => 'fifty',
				'fourty' => 'fourty',
				'thirty' => 'thirty',
				'twenty-five' => 'twenty-five',
				'twenty' => 'twenty',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_54ee142352272',
			'label' => 'Icon Appearance',
			'name' => 'icon_appearance',
			'prefix' => '',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array (
				'circle' => 'circle',
				'rounded' => 'rounded',
				'square' => 'square',
			),
			'other_choice' => 0,
			'save_other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
		),
		array (
			'key' => 'field_542989555d625',
			'label' => 'Social Networks',
			'name' => 'social_networks',
			'prefix' => '',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'layout' => 'table',
			'button_label' => 'Add Row',
			'sub_fields' => array (
				array (
					'key' => 'field_542989745d626',
					'label' => 'Social Network URL',
					'name' => 'social_network_url',
					'prefix' => '',
					'type' => 'text',
					'instructions' => 'Url of social network page.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
					'readonly' => 0,
					'disabled' => 0,
				),
				array (
					'key' => 'field_542987745d623',
					'label' => 'Social Icon',
					'name' => 'social_icon',
					'prefix' => '',
					'type' => 'radio',
					'instructions' => 'Choose social network to display on this site.',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array (
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array (
						'Facebook' => 'Facebook',
						'Flickr' => 'Flickr',
						'Instagram' => 'Instagram',
						'Linkedin' => 'Linkedin',
						'Pinterest' => 'Pinterest',
						'Twitter' => 'Twitter',
						'Vimeo' => 'Vimeo',
						'YouTube' => 'YouTube',
					),
					'other_choice' => 0,
					'save_other_choice' => 0,
					'default_value' => '',
					'layout' => 'vertical',
				),
			),
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-social-networks',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;

//	Advanced Custom Fields Pro Options Page
//	http://www.advancedcustomfields.com/resources/options-page/

if( function_exists('acf_add_options_page') ) {
	
	acf_add_options_page();
	
}

if( function_exists('register_field_group') ):

register_field_group(array (
	'key' => 'group_5464f860ced58',
	'title' => 'Header & Footer',
	'fields' => array (
		array (
			'key' => 'field_5464f8732d88d',
			'label' => 'Logo',
			'name' => 'logo_header',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),


		array (
			'key' => 'field_546508b5804f3',
			'label' => 'Logo Footer',
			'name' => 'logo_footer',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_5464f8832d88e',
			'label' => 'Link url for header logo',
			'name' => 'url_header',
			'prefix' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'http://www.pitzer.edu',
			'placeholder' => '',
		),
		array (
			'key' => 'field_546508dd804f4',
			'label' => 'Link url for footer logo',
			'name' => 'url_footer',
			'prefix' => '',
			'type' => 'url',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => 'http://www.pitzer.edu',
			'placeholder' => '',
		),
		array (
			'key' => 'field_54650e9fb5b51',
			'label' => 'Watermark',
			'name' => 'watermark',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
		array (
			'key' => 'field_54651a271b364',
			'label' => 'Banner Image',
			'name' => 'image_banner',
			'prefix' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'array',
			'preview_size' => 'thumbnail',
			'library' => 'all',
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

// Footer contact Information
register_field_group(array (
	'key' => 'group_546bbbcf710d6',
	'title' => 'Footer Contact Info',
	'fields' => array (
		array (
			'key' => 'field_546bbc8ea7d46',
			'label' => 'Office Name',
			'name' => 'office',
			'prefix' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Office of Communications',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546bbe69a7d47',
			'label' => 'Office Location',
			'name' => 'location',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => 'On campus office location.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Scott Hall 100',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546bbefca7d48',
			'label' => 'Phone Numbers',
			'name' => 'phone',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => 'Add each number on a separate line.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '909.555.5555
Fax: 909.555.5555',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546bbf4fa7d49',
			'label' => 'Address',
			'name' => 'address',
			'prefix' => '',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '1050 N. Mills Avenue
Claremont, CA 91711',
			'placeholder' => '',
			'maxlength' => '',
			'rows' => 3,
			'new_lines' => 'br',
			'readonly' => 0,
			'disabled' => 0,
		),
		array (
			'key' => 'field_546bbf88a7d4a',
			'label' => 'Email',
			'name' => 'email',
			'prefix' => '',
			'type' => 'text',
			'instructions' => 'Use a general email address.
When "Office Name" is clicked it will open an email to the provided address.
',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array (
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
			'readonly' => 0,
			'disabled' => 0,
		),
	),
	'location' => array (
		array (
			array (
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
));

endif;
